swagger: '2.0'
info:
  version: '0.1'
  title: bulb
  description: growth
host: dev.buttaface.space
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  '/documents/{doc_id}':
    parameters:
      - name: doc_id
        in: path
        required: true
        type: string
    get:
      operationId: api.handlers.get_document
      summary: Get Document
      tags:
        - Documents
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/document-output'
          examples:
            application/json:
              id: f2ebd8dd-86be-41d9-8ee9-858a34ec21e2
              create_datetime: '2775-01-21T18:55:35.400Z'
              organization: 0e8eadfa-c8c6-4eae-a256-f9093b85662d
              uri: 'https://bulb-documents.s3.amazonaws.com/410741ff-e2f1-4b42-a4de-84cd91129371'
              due_date: '2017-04-26T22:21:23Z'
              progress: 0.33
              status: DONE
              name: state tax filing
              type: FORM
    put:
      operationId: api.handlers.update_document
      summary: Update Document
      tags:
        - Documents
      parameters:
        - name: body
          in: body
          schema:
            $ref: '#/definitions/document-input'
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/document-output'
    delete:
      operationId: api.handlers.delete_document
      summary: Delete Document
      tags:
        - Documents
      responses:
        '204':
          description: ''
  /documents:
    get:
      operationId: api.handlers.list_documents
      summary: List Documents
      tags:
        - Documents
      parameters:
        - $ref: '#/parameters/trait:paged:offset'
        - $ref: '#/parameters/trait:paged:limit'
      responses:
        '200':
          description: ''
          schema:
            type: array
            items:
              $ref: '#/definitions/document-output'
          examples:
            application/json:
              - id: f2ebd8dd-86be-41d9-8ee9-858a34ec21e2
                create_datetime: '2775-01-21T18:55:35.400Z'
                organization: 0e8eadfa-c8c6-4eae-a256-f9093b85662d
                uri: 'https://bulb-documents.s3.amazonaws.com/410741ff-e2f1-4b42-a4de-84cd91129371'
                due_date: '2017-04-26T22:21:23Z'
                progress: 0.33
                status: DONE
                name: state tax filing
                type: FORM
    post:
      operationId: api.handlers.create_document
      summary: Create Document
      tags:
        - Documents
      parameters:
        - name: body
          in: body
          schema:
            $ref: '#/definitions/document-input'
      responses:
        '201':
          description: ''
          schema:
            $ref: '#/definitions/document-output'
  '/organizations/{org_id}':
    parameters:
      - name: org_id
        in: path
        required: true
        type: string
    get:
      operationId: api.handlers.get_organization
      summary: Get Organization
      tags:
        - Organizations
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/organization-output'
          examples:
            application/json:
              id: ca32d93f-5af6-43d1-a5bd-da4f5152c9d0
              type: BUYER
              name: bob's burgers
              users:
                - b85769c0-5b80-4759-ae06-5881e8c85d77
                - af125212-7e30-47be-b932-9baf821a615f
                - af93193a-9e57-4430-8c4e-623d9c4549d1
    put:
      operationId: api.handlers.update_organization
      summary: Update Organization
      tags:
        - Organizations
      parameters:
        - name: body
          in: body
          schema:
            $ref: '#/definitions/organization-input'
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/organization-output'
    delete:
      operationId: api.handlers.delete_organization
      summary: Delete Organization
      tags:
        - Organizations
      responses:
        '204':
          description: ''
  /organizations:
    get:
      operationId: api.handlers.list_organizations
      summary: List Organizations
      tags:
        - Organizations
      parameters:
        - $ref: '#/parameters/trait:paged:offset'
        - $ref: '#/parameters/trait:paged:limit'
      responses:
        '200':
          description: ''
          schema:
            type: array
            items:
              $ref: '#/definitions/organization-output'
          examples:
            application/json:
              - id: ca32d93f-5af6-43d1-a5bd-da4f5152c9d0
                type: BUYER
                name: bob's burgers
                users:
                  - b85769c0-5b80-4759-ae06-5881e8c85d77
                  - af125212-7e30-47be-b932-9baf821a615f
                  - af93193a-9e57-4430-8c4e-623d9c4549d1
    post:
      operationId: api.handlers.create_organization
      summary: Create Organization
      tags:
        - Organizations
      parameters:
        - name: body
          in: body
          schema:
            $ref: '#/definitions/organization-input'
      responses:
        '201':
          description: ''
          schema:
            $ref: '#/definitions/organization-output'
  '/resources/{res_id}':
    parameters:
      - name: res_id
        in: path
        required: true
        type: string
    get:
      operationId: api.handlers.get_resource
      summary: Get Resource
      tags:
        - Resources
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/resource-output'
          examples:
            application/json:
              id: 25fbb904-1b71-4564-b246-093c286be335
              create_datetime: '2003-10-18T05:14:26.976Z'
              name: MD State Income Tax Filing 2017
              processing_time: 30
              status: IN_PROGRESS
              type: FORM
              uri: 'https://bulb-resources.s3.amazonaws.com/c166bf45-0421-4df1-9fb6-b5cf091ae57d'
    put:
      operationId: api.handlers.update_resource
      summary: Update Resource
      tags:
        - Resources
      parameters:
        - name: body
          in: body
          schema:
            $ref: '#/definitions/resource-input'
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/resource-output'
    delete:
      operationId: api.handlers.delete_resource
      summary: Delete Resource
      tags:
        - Resources
      responses:
        '204':
          description: ''
  /resources:
    get:
      operationId: api.handlers.list_resources
      summary: List Resources
      tags:
        - Resources
      parameters:
        - $ref: '#/parameters/trait:paged:offset'
        - $ref: '#/parameters/trait:paged:limit'
      responses:
        '200':
          description: ''
          schema:
            type: array
            items:
              $ref: '#/definitions/resource-output'
          examples:
            application/json:
              - id: 25fbb904-1b71-4564-b246-093c286be335
                create_datetime: '2003-10-18T05:14:26.976Z'
                name: MD State Income Tax Filing 2017
                processing_time: 30
                status: IN_PROGRESS
                type: FORM
                uri: 'https://bulb-resources.s3.amazonaws.com/c166bf45-0421-4df1-9fb6-b5cf091ae57d'
    post:
      operationId: api.handlers.create_resource
      summary: Create Resource
      tags:
        - Resources
      parameters:
        - name: body
          in: body
          schema:
            $ref: '#/definitions/resource-input'
      responses:
        '201':
          description: ''
          schema:
            $ref: '#/definitions/resource-output'
  '/users/{user_id}':
    parameters:
      - name: user_id
        in: path
        required: true
        type: string
    get:
      operationId: api.handlers.get_user
      summary: Get User
      tags:
        - Users
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/user-output'
          examples:
            application/json:
              id: 7a0ab3bb-a0f6-4a94-9f1f-dcc2210d8efe
              create_datetime: '5042-03-13T05:13:35.233Z'
              email: bob@bobsburgers.com
              organizations:
                - c0d803db-8ab2-429c-bfa1-b17afdd18b5d
              name: bob
    put:
      operationId: api.handlers.update_user
      summary: Update User
      tags:
        - Users
      parameters:
        - name: body
          in: body
          schema:
            $ref: '#/definitions/user-input'
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/user-output'
    delete:
      operationId: api.handlers.delete_user
      summary: Delete User
      tags:
        - Users
      responses:
        '204':
          description: ''
  /users:
    get:
      operationId: api.handlers.list_users
      summary: List Users
      tags:
        - Users
      parameters:
        - $ref: '#/parameters/trait:paged:offset'
        - $ref: '#/parameters/trait:paged:limit'
      responses:
        '200':
          description: ''
          schema:
            type: array
            items:
              $ref: '#/definitions/user-output'
          examples:
            application/json:
              - id: 7a0ab3bb-a0f6-4a94-9f1f-dcc2210d8efe
                create_datetime: '5042-03-13T05:13:35.233Z'
                email: bob@bobsburgers.com
                organizations:
                  - c0d803db-8ab2-429c-bfa1-b17afdd18b5d
                name: bob
    post:
      operationId: api.handlers.create_user
      summary: Create User
      tags:
        - Users
      parameters:
        - name: body
          in: body
          schema:
            $ref: '#/definitions/user-input'
      responses:
        '201':
          description: ''
          schema:
            $ref: '#/definitions/user-output'
parameters:
  'trait:paged:offset':
    name: offset
    in: query
    description: Offset from which to start list of returned values.
    type: integer
    default: 0
    minimum: 0
  'trait:paged:limit':
    name: limit
    in: query
    description: 'Maximum number of items to return. This should be an integer on the interval [1,65536].'
    type: integer
    minimum: 1
    exclusiveMinimum: false
    maximum: 65544
    exclusiveMaximum: false
responses:
  'trait:standardErrors:404':
    description: ''
    schema:
      type:
        - object
        - string
      description: Entity not found.
      additionalProperties: false
  'trait:standardErrors:500':
    description: ''
    schema:
      type:
        - object
        - string
      description: Internal server error.
      additionalProperties: false
definitions:
  document:
    title: Document
    type: object
    additionalProperties: false
    properties:
      organization:
        type: string
        format: uuid
        description: UUID of Organization with which the Document is associated.
      uri:
        type: string
        format: uri
        description: URI where the actual Document is located.
      due_date:
        type: string
        format: date-time
        description: Datetime representing when the Document it due.
      progress:
        type: number
        default: 0
        minimum: 0
        maximum: 1
        description: 'Decimal numer on the interval [0,1] representing the progress towards completion of the Document as a percentage.'
      status:
        type: string
        default: NOT_STARTED
        enum:
          - NOT_STARTED
          - IN_PROGRESS
          - DONE
          - NOT_APPLICAPLE
      name:
        type: string
        pattern: '^[A-Za-z0-9_ -]+'
      type:
        type: string
        enum:
          - GUIDE
          - TEMPLATE
          - FORM
      note:
        type: string
        maxLength: 140
        description: A short note to be attached to the document.
    example:
      organization: 0e8eadfa-c8c6-4eae-a256-f9093b85662d
      uri: 'https://bulb-documents.s3.amazonaws.com/410741ff-e2f1-4b42-a4de-84cd91129371'
      due_date: '2017-04-26T22:21:23Z'
      progress: 0.33
      status: DONE
      name: state tax filing 2017
      type: FORM
      note: this is our master document for tax season '17. pilfering washington politicians...
  document-readonly:
    title: Document ReadOnly
    type: object
    properties:
      doc_id:
        type: string
        format: uuid
        description: UUID for the document. This value is guaranteed to be unique amongst documents
      create_datetime:
        type: string
        format: date-time
        description: datetime string representing document creation time.
    required:
      - doc_id
    example:
      id: 246bfd6d-2aed-47d7-8fde-cb05aabfcd4f
      create_datetime: '2017-04-16T13:49:13Z'
  entity:
    title: Entity
    type: object
    description: 'This object represents an abstract bulb Entity, which can represent any of the primary endpoint Models.'
    properties:
      entity_id:
        type: string
        format: uuid
        description: The UUID of the entity in its respective domain.
      type:
        type: string
        enum:
          - USER
          - ORGANIZATION
          - DOCUMENT
          - RESOURCE
    example:
      entity_id: f754c40d-e6cd-4d58-aaf5-2a487f421498
      type: USER
  organization:
    title: Organization
    type: object
    additionalProperties: false
    properties:
      type:
        type: string
        enum:
          - BUYER
          - VENDOR
        default: BUYER
      name:
        type: string
        pattern: '[a-zA-Z0-9-_ '']+'
      users:
        type: array
        description: list of users (by `user_id` ) who are members of the organization.
        items:
          type: string
          format: uuid
    example:
      type: BUYER
      name: bob's burgers
      users:
        - b85769c0-5b80-4759-ae06-5881e8c85d77
        - af125212-7e30-47be-b932-9baf821a615f
        - af93193a-9e57-4430-8c4e-623d9c4549d1
  organization-readonly:
    title: Organization ReadOnly
    type: object
    properties:
      org_id:
        type: string
        format: uuid
        description: UUID for the organization. This value is guaranteed to be unique amongst organizations.
      create_datetime:
        type: string
        format: date-time
        description: datetime string representing organization creation datetime.
    required:
      - org_id
    example:
      id: 246bfd6d-2aed-47d7-8fde-cb05aabfcd4f
      create_datetime: '2017-04-16T13:49:13Z'
  resource:
    title: Resource
    type: object
    additionalProperties: false
    properties:
      name:
        type: string
        pattern: '^[A-Za-z0-9_ -]+'
      url:
        type: string
        format: uri
        description: 'TODO: deduplicate this property with Document.uri'
      mailto_uri:
        type: string
        pattern: '^mailto:.+\@.+\..+$'
      s3_thumbnail_uri:
        type: string
        format: uri
    example:
      name: Maryland Chamber of Commerce
      url: 'https://www.mdchamber.org/'
      s3_thumbnail_uri: 'https://bulb-resources.s3.amazonaws.com/MD_Chamber_of_Commerce.png'
      mailto_uri: 'mailto:jpalmeri@mdchamber.org'
  resource-readonly:
    title: Resource ReadOnly
    type: object
    properties:
      res_id:
        type: string
        format: uuid
        description: UUID for the resource. This value is guaranteed to be unique amongst resources.
      create_datetime:
        type: string
        format: date-time
        description: datetime string representing resource creation datetime.
    required:
      - res_id
    example:
      id: 246bfd6d-2aed-47d7-8fde-cb05aabfcd4f
      create_datetime: '2017-04-16T13:49:13Z'
  user:
    title: User
    type: object
    additionalProperties: false
    properties:
      email:
        type: string
        format: email
      organizations:
        type: array
        description: a list of organizations (by id) that the user is a member of.
        uniqueItems: true
        items:
          type: string
          format: uuid
      name:
        type: string
        pattern: '^[A-Za-z-_ ]+'
    example:
      email: bob@bobsburgers.com
      organizations:
        - c0d803db-8ab2-429c-bfa1-b17afdd18b5d
      name: bob
  user-readonly:
    title: User ReadOnly
    type: object
    properties:
      user_id:
        type: string
        format: uuid
        description: UUID for the user. This value is guaranteed to be unique amongst users.
      create_datetime:
        type: string
        format: date-time
        description: datetime string representing user creation datetime.
    required:
      - user_id
    example:
      id: 246bfd6d-2aed-47d7-8fde-cb05aabfcd4f
      create_datetime: '2017-04-16T13:49:13Z'
  user-input:
    title: User Input
    $ref: '#/definitions/user'
  user-output:
    title: User Output
    allOf:
      - $ref: '#/definitions/user-readonly'
      - $ref: '#/definitions/user-input'
  organization-input:
    title: Organization Input
    $ref: '#/definitions/organization'
  organization-output:
    title: Organization Output
    allOf:
      - $ref: '#/definitions/organization-readonly'
      - $ref: '#/definitions/organization-input'
  document-input:
    title: Document Input
    $ref: '#/definitions/document'
  document-output:
    title: Document Output
    allOf:
      - $ref: '#/definitions/document-readonly'
      - $ref: '#/definitions/document-input'
  resource-input:
    title: Resource Input
    $ref: '#/definitions/resource'
  resource-output:
    title: Resource Output
    allOf:
      - $ref: '#/definitions/resource-readonly'
      - $ref: '#/definitions/resource-input'